### ISSUE TITLE
Question: Init state with hook

### ISSUE THREAD

**Issue by adriano-tirloni** [atlassian/react-sweet-state#103]
Is it possible to have an initial state set when using the hook API?

I was able to achieve it using the container like in the doc example. 
I was thinking something in the line of useState.

Thanks.

**Comment by albertogasparin** [comment]
You could but it is a bad pattern and might cause issues with React future improvements.
Basically when you do:

```js
const [data, { setData }] = useData();
if (!data) setData(true);
``` 

1.  you might call that function multiple times if the component re-renders again before `data` is updated
2.  you will trigger an additional re-render, because that component is already subscribed to the store

Even wrapping `setData` with `useMemo` might not be enough as Concurrent Mode might run it twice anyway.
Given React owns the re-render schedule and when it happens, you better stick with patterns that ensure data consistency. 

Indeed, Containers work in a different way, and the `onInit/onUpdate` functions ensure that the effects are called only when needed as they rely on the component lifecycle.
However, if you are using the global scope, wrapping your tree in Containers is not mandatory. They are unlikely to cause performance issues, but you can add them as sibling of your main tree, before the consumers, and they will work fine anyway :) 

```jss
const Root = () => (
  <>
    <DataContainer data={true} isGlobal />
    <MyApp />
  <>
);
```

^ The above works when either `isGlobal` or `scope` are set, but remember that to access scoped stores you need a wrapping container anyway

**Comment by adriano-tirloni** [comment]
Thanks for the reply Alberto, is was able to achieve my need without getting into questionable pattern using a null selector with actions in a previous point in the tree, where I already had access to the state I was going to need downwards.

The isGlobal Container was not needed.

BTW, I'm using NextJs and for some reason react-sweet-state is not playing nicely with its Hot Reload Module, I have to restart the server almost every time a change is made in sweet-state files. Not sure if there is a conflict in my project, but if this does happen might be nice to point out in docs so we are not chasing "intermittent bugs".

**Comment by albertogasparin** [comment]
Cool.
Regarding NextJs would you mind opening a separate issue? I don't use it so it might take some time before have time to investigate, but can help letting other people know if they experience inconsistencies. Thanks
