### ISSUE TITLE
Move from .js to .ts

### ISSUE THREAD

**Issue by rajanlagah** [atlassian/react-sweet-state#213]
![Screenshot from 2023-08-20 00-10-20](https://github.com/atlassian/react-sweet-state/assets/20952569/e9efaa0d-56aa-40cd-b43e-05bf484948eb)

is there any specific reason that we are not switching to .ts?

**Comment by albertogasparin** [comment]
The reason why you see those errors is because those files are using [Flow types](https://flow.org), instead of Typescript types. 
The library still supports consumers using that instead of TS, but VSCode is not happy and unnecessary complains as it does not really support both type systems at the same time. 

We can probably drop support for it too in next major, and migrate those files to tsx.
