### ISSUE TITLE
How can I emit action from other store?

### ISSUE THREAD

**Issue by cytrowski** [atlassian/react-sweet-state#34]
I have a case where I have an async action in which I want to emit action from different store. Is that possible? Or should I combine this kind of logic on the component level using hooks?

**Comment by albertogasparin** [comment]
Currently there is no built-in functionality to do that. You'll have to do it as you would handle it via `useState` hooks. So you should compose the render props components/hooks and trigger events on state change (so that composition becomes like a controller). In case you need something more customisable, you can always pass the secondary action as an argument of the primary one, however this patter might get hard to manage in the long term.
