### ISSUE TITLE
Deprecate actions property in action thunk

### ISSUE THREAD

**Issue by albertogasparin** [atlassian/react-sweet-state#37]
Having all actions available in the action thunk is handy but it is a nightmare to type as you are required to use recursive types. 
Better to stick with the same pattern as redux, where you call `dispatch(action())`.

- [x] Publish Typescript types without `actions` support
- [x] Remove `actions` arg from docs 
- [x] Expose new `ActionApi` in Flow
- [x] Migrate examples to `dispatch`

**Comment by albertogasparin** [comment]
We are going to remove the support in v2, for now we remove the documentation for it and publish Typescript types without support for it (as recursive types are not supported anyway so it was never going to work)

**Comment by joshuatvernon** [comment]
I'm actually trying right now to have optional `actions`. Since I'd like to create a `createStore` function that accepts different permutations of the actions as different users of the store will only need (and should have access to) different actions.

I actually have this recursive type in Typescript I made to do recursive partial but it doesn't seem to work with the `ActionThunk`
```
export type RecursivePartial<T> = {
  [P in keyof T]?: RecursivePartial<T[P]>;
};
```

Any chance of being able to support this so I can do this e.g.
```
export const createStoreInstance = (
  initialState: RecursivePartial<State>,
  actions: RecursivePartial<Actions>,
  storeName: string
) => {
  return createStore<RecursivePartial<State>, RecursivePartial<Actions>>({
    initialState,
    actions,
    storeName
  });
};
```

**Comment by albertogasparin** [comment]
Can you provide a code example (for instance on codesandbox)? 
Also this ticket is to deprecate the `actions` access in the thunk function ( `const myAction = () => ({ actions }) => ...` not sure the issue you are describing is related. 
If not feel free to open a dedicated issue so we can better discuss the options

**Comment by albertogasparin** [comment]
As of `v2.5.0` Flow `Action` does not accept `Actions` anymore. `actions` are still available in code but they will be typed to any (Typescript never supported it anyway).
