### ISSUE TITLE
Problem using with useEffect

### ISSUE THREAD

**Issue by lambdakris** [atlassian/react-sweet-state#77]
I have a really simple example that I can't seem to get working. The idea is simply to display whether the component is loading or not, with the action for the background work being dispatched in a useEffect hook. However, after the work is done and the state gets updated, the component doesn't seem to re-render, and I just can't figure out why, so I assume I must be doing something wrong. Attached is the example "sweet.zip", hopefully somebody else can quickly determine what's going on.

[sweet.zip](https://github.com/atlassian/react-sweet-state/files/4489451/sweet.zip)

**Comment by lambdakris** [comment]
It seems like it might have to do with doing work in a promise or a callback, but I have not been able to find a way to change the setState call so that it causes the component to re-render. I have tried applying the example from https://atlassian.github.io/react-sweet-state/#/advanced/actions?id=async-actions, but it also does not work (the part after the await runs and setState is called, but the component does not re-render).

**Comment by lambdakris** [comment]
Ok, it looks like React.StrictMode has something to do with it. 

When I run the following, the UI for "Async Loading" does not re-render after the promise resolves:

```
import React from 'react';
import ReactDOM from 'react-dom';
import {
  createStore,
  createHook,
  StoreActionApi,
} from 'react-sweet-state';

type State = {
  isLoadingSync: boolean
  isLoadingAsync: boolean
};

const initialState: State = {
  isLoadingSync: true,
  isLoadingAsync: true,
};

const actions = {
  loadSync: () => (store: StoreActionApi<State>) => {
      store.setState({ isLoadingSync: false });
  },
  loadAsync: () => async (store: StoreActionApi<State>) => {
      await new Promise(r => setTimeout(r, 4000));

      store.setState({ isLoadingAsync: false });
  }
};

const Store = createStore({
  initialState,
  actions,
});

const useLoadingStore = createHook(Store);

const LoaderView = () => {
  const [state, actions] = useLoadingStore();

  React.useEffect(() => {
      actions.loadSync();
      actions.loadAsync();
  }, [actions]);

  return <>
    <h3>Sync Loading: { state.isLoadingSync ? 'Pending' : 'Finished' }</h3>
    <h3>Async Loading: { state.isLoadingAsync ? 'Pending' : 'Finished' }</h3>
  </>
};

const App = () => (
  <div>
    <h2>Loading example</h2>
    <LoaderView />
  </div>
);

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```
However, if I remove React.StrictMode from around App, the UI for "Async Loading" will re-render:
```
...

ReactDOM.render(
  <App />,
  document.getElementById('root')
);
```

Yet another thing that causes the UI for "Async Loading" to re-render (even with React.StrictMode) is if I introduce a dummy state hook (forceUpdate) and combine it with the store state, like so:
```
...

const LoaderView = () => {
  const [forceUpdate,setForceUpdate] = React.useState(true);
  const [state, actions] = useLoadingStore();

  React.useEffect(() => {
      actions.loadSync();
      actions.loadAsync();
  }, [actions]);

  if (forceUpdate && !state.isLoadingAsync) {
    setForceUpdate(false);
  }
  
  return <>
    <h3>Sync Loading: { state.isLoadingSync ? 'Pending' : 'Finished' }</h3>
    <h3>Async Loading: { state.isLoadingAsync ? 'Pending' : 'Finished' }</h3>
  </>
};

...

```

At this point I'm not exactly sure what the right thing to do is. Whether it is adequate to remove React.StrictMode from the App root, or whether I am actually using the react-sweet-state hook incorrectly and there is a way to use it that will cause re-renders similar to a state hook.

Here is the latest example project that contrasts sync with async behavior, and which you can use to test out my findings above (remove React.StrictMode, forceUpdate state hook, etc.)

[sweet.zip](https://github.com/atlassian/react-sweet-state/files/4494722/sweet.zip)

**Comment by albertogasparin** [comment]
Started looking at this today and you are indeed right: it is due to a behaviour of `StrictMode` (only in development): React is calling [some lifecycle events twice](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) in order to let you spot dangerous side effects.

I found out that this is causing an internal sweet-state optimisation to call `setState` on the first invocation but not on the second (double) one. So one react tree gets `isLoading: false` while the other skips calling `setState` as the refs inside the component are already up to date with the new state.

I'll evaluate what are the performance implications of removing that check (or if there is a workaround).

**Comment by albertogasparin** [comment]
I believe one of the reasons the bug is triggered only on async actions is because updates are batched by default on interactions while not yet on async effects. That is also why I did not spot this issue while using sweet-state with react concurrent, as batching is enabled by default.

Indeed, if you add a sweet-state middleware to batch updates then the issue disappears:

```js
import ReactDOM from 'react-dom';
import { defaults } from 'react-sweet-state';

const batchedMw = () => next => fn => {
  let result;
  ReactDOM.unstable_batchedUpdates(() => { result = next(fn); });
  return result;
};
defaults.middlewares.add(batchedMw);

// ...
ReactDOM.render(...)
```

However this might still be a smell that something might break
