### ISSUE TITLE
Testing composed actions

### ISSUE THREAD

**Issue by ninjz** [atlassian/react-sweet-state#78]
I am a little confused with the example posted in the docs [here](https://atlassian.github.io/react-sweet-state/#/testing/actions?id=composed-actions) about testing for composed actions. 

If I wanted to assert that `clickAnalytics` is being dispatched inside of `clickManager` how would I go about that? It seems if I want to check if the mocked dispatch fn is being called I would only be able to check if there was some call to dispatch using `expect.any(Function)` since it would do a comparison on an anonymous fn but I wouldn't be able to assert if it was exactly `clickAnalytics` that was being called. 

Is there any other way that I'm missing? Or does it suffice to make an assertion that somewhere dispatch is being called with some function?

**Comment by albertogasparin** [comment]
So, it depends what you want to assess. In that example both `clickAnalytics` and `clickManager` are public. So you can not only test that `clickAnalytics` has been called, but also that dispatch has been called with the result thunk of `clickAnalytics`, by using `jest.spyOn` and tweaking the code to call the action from an object:

```js
export const actions = {
   clickAnalytics: () => ({ setState, getState }) => { ... },
   clickManager: () => ({ setState, getState, dispatch }) => {
      // ...
      dispatch(actions.clickAnalytics());
   },
}
```

(as you cannot override/spy on `clickAnalytics` if you don't have access to it). 
Now in your test you can do:

```js
const clickAnalyticsThunkMock = jest.fn();
jest.spyOn(actions, 'clickAnalytics').mockImplementation(() => clickAnalyticsThunkMock);
// ...
clickManager()(argsMock);
expect(actions.clickAnalytics).toHaveBeenCalled();
expect(argsMock.dispatch).toHaveBeenCalledWith(clickAnalyticsThunkMock)
```

Different story if you want to keep your action "private". As you cannot override nor spy on it, it is better to test the input state and output state or the calls to `setState`. Given `setState` is a mock you provide, you can make it mutate an initial object or simply assess that it has been called with `{ lastAnalytics: 123456 }`.

This second way allows you cover the entire action by its effects (the things that you really care about) instead of the internal implementation (so ignoring the fact that you dispatch another action).

In the end it is matter of taste: pure unit tests or more integration-like tests? (I believe both options are valid and have pros and cons, so pick the style that you like most or makes more sense for your project)

**Comment by ninjz** [comment]
@albertogasparin Thanks for the detailed response. I ended up going with the more integration-like approach, it took me a bit to figure out how to assess setState was being called with the right params within the composed action but I figured it out, just going to place this here in case anyone else is struggling with this because it wasn't initially obvious to me.

```tsx
const setState = jest.fn()
const getState = jest.fn()
const dispatch = jest.fn()

dispatch.mockImplementation((action) => action({setState, getState}))
// ...
await thunk({ setState, getState, dispatch })
expect(setState).toHaveBeenCalledWith({...expected})
```
